name = "gomoku-online"
main = "worker.js"
compatibility_date = "2026-09-03"

[assets]
directory = "./public"
binding = "ASSETS"

[durable_objects]
bindings = [{ name = "GAME", class_name = "Game" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Game"]